# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySLwoTX31y1D9CpyqCNRhHNIPhjvSNmj
"""

def kasallik (belgi):
    if belgi=="Isitma":
      return "Parasetamol iching"
    elif belgi=="Bosh oģriģi":
      return "Bolnol iching"
    elif belgi=="Tomoq oģrigi":
      return "Mukaltin iching"
    else:
      return "Shifokorga murojaat qiling"
belgi=input("kasallik belgisini kiriting")
natija=kasallik(belgi)
print (natija)

import pandas as pd

jadval={
"ism":["Manzura", "Ali"],
"familiya":["Mòsinova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qòqon shahar"]


}
baza=pd.DataFrame(jadval)
print(baza)

#filtr=baza[baza["yoshi"]<20]
#print(filtr)

#filtr=baza[baza["manzili"]=="Farģona shahar"]
#print(filtr)

#titanik=pd.read_csv("/content/tested (1).csv")
#print(titanik)

#filtr=titanik[titanik['Age']<15]
#print(filtr)

import pandas as pd

jadval={
"ism":["Gulmira", "Ali"],
"familiya":["Abdukarimova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qòqon shahar"]


}
baza=pd.DataFrame(jadval)
print(baza)

#filtr=baza[baza["yoshi"]<20]
#print(filtr)

#filtr=baza[baza["manzili"]=="Farģona shahar"]
#print(filtr)

#titanik=pd.read_csv("/content/tested (1).csv")
#print(titanik)

#filtr=titanik[titanik['Age']<15]
#print(filtr)

def kitob_tavsiya(janr):
   if janr == "Detektiv":
      return "Sherlok Xolms kitobini o'qing"
   elif janr == "Romantika":
      return "O'tkan kunlar kitobini o'qing"
   elif janr == "Fantastika":
      return "Garri Potter kitobini o'qing"
   elif janr == "Ilmiy":
      return "Sun'iy intellekt  asoslari kitobini o'qing"
   else:
      return "Kutubxonaga murojaat qiling"
janr = input("Qanday janrdagi kitob kerak? ")
natija = kitob_tavsiya(janr)
print(natija)

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6,250])
y=np.array([0,250,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6])
y=np.array([0,250,250,6])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6,0])
y=np.array([0,250,250,0,0])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array ([0,0,5,0])
y=np.array([0,200,125,0])
plt.plot(x,y, 'd--y')
plt.show()

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target
# Ma'lumotlarni o'qitish va sinov to'plamlariga bo'lish
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.3, random_state=42)
# K-NN modelini yaratish va o'qitish
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
# Sinov to'plamidagi natijalarni baholash
y_pred = knn.predict(X_test)
print(f"K-NN algoritmining aniqligi: {accuracy_score(y_test, y_pred)}")

from sklearn.svm import SVC
# SVM modelini yaratish va o'qitish
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
# Sinov to'plamida natijalarni baholash
y_pred_svm = svm_model.predict(X_test)
print(f"SVM algoritmining aniqligi: {accuracy_score(y_test,
y_pred_svm)}")

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target

# Ma'lumotlarni o'qitish va sinov to'plamlariga bo'lish
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Logistic Regression modelini yaratish va o'qitish
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Sinov to'plamida bashorat qilish
y_pred = model.predict(X_test)

# Aniqlikni tekshirish
print("Logistic Regression aniqligi:", accuracy_score(y_test, y_pred))

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Iris datasetini yuklash
iris = load_iris()
X = iris.data
y = iris.target

# Ma'lumotlarni train va testga bo'lish
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# SVM modelini yaratish va o'qitish
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Bashorat qilish
y_pred_svm = svm_model.predict(X_test)

# Aniqlikni hisoblash
print("SVM algoritmining aniqligi:", accuracy_score(y_test, y_pred_svm))

!pip install gtts

from gtts import gTTS
import os
text="Assalomu alaykum hurmatli talabalar"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ru"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ru.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="en"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_en.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ar"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ar.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="fr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_fr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="zh"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="zh-TW"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh-TW.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="de"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_de.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="es"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_es.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ja"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ja.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Abdukarimova Gulmira bòlaman"
language="ko"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ko.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)